name: Deploy Dev
on:
  push:
    branches:
      - main

  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Print branch name
        run: echo "Branch name is ${{ steps.extract_branch.outputs.branch }}"
